config/routes.rb
Rails.application.routes.draw do
  # get "welcome", to: "albums#index"
  # get "eliminar", to: "ablbums#destroy"
  resources :albums
  root "albums#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :tracks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end
  
  def show
    @albums = Album.all
    @album = Album.find(params[:id]) 
    @tracks = @album.tracks 

  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<div class="row">
<% @albums.each do |album|%>
  <div class="col-md-3">
    <%= link_to(album) do %>
      <div class="thumbnail">
        <img src="<%= album.cover %>">
        <div class="caption">
          <h3 class="title"> <%= album.title %> </h3>
          <p class="artist"> <%= album.artist %> </p>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
  
</div>

app/views/albums/show.html.erb
<% @albums.each do |album|%>
  <% if album == @album %>
    <div class="col-md-3">
      <%= link_to(album) do %>
        <div class="thumbnail">
          <img src="<%= album.cover %>">
          <div class="caption">
            <h3 class="title"> <%= album.title %> </h3>
            <p class="artist"> <%= album.artist %> </p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

<div class="show row">
  <div class="cover col-md-4">  </div>

  <div class="col-sm-8">
    <h3 class="album-title">  </h3>
    <p class="album-artist">  </p>
    
    <% @tracks.each do |track|%>
      <div class="track row">
        <div class="name col-md-8"> <%= track.name %></div>
        <div class="minutes col-md-4"> <%= track.minutes %> min</div>
      </div>
    <% end %>
    <%= link_to "Menu", albums_path%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BassMusic</title>
    <link rel="stylesheet" href="http://content.codecademy.com/projects/bootstrap.min.css">
    <link href='http://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <img class="logo" src="https://static-assets.codecademy.com/Courses/learn-ruby-on-rails/BassMusic/logo.svg"/>
      </div>
    </div>

    <div class="main">
      <div class="container">

        <%= yield %>
      
      </div>
    </div>

    <div class="footer">
      <div class="container">
        <div class="col-md-2">
          <h3>Bass</h3>
          <ul>
            <li><a href="#">Install</a></li>
            <li><a href="#">Mobile</a></li>
          </ul>
        </div>
        <div class="col-md-2">
          <ul>
            <h3>About</h3>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Team</a></li>
            <li><a href="#">Jobs</a></li>
          </ul>
        </div>
        <div class="col-md-2">
          <ul>
            <h3>Support</h3>
            <li><a href="#">Help Center</a></li>
            <li><a href="#">Get Started</a></li>  
            <li><a href="#">Contact Us</a></li>
          </ul>
        </div>
        <div class="col-md-2">
          <ul>
            <h3>Community</h3>
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Google+</a></li>
          </ul>
        </div>
      </div>
    </div>

  </body>
</html>